### PR TITLE
Merge volunteer sign up into Master

### PR DESCRIPTION
**Pull request by mleong245**
Parity between master and volunteer_sign_up branch.  The volunteering_sign_up feature still needs to be refactored to be proper Cucumber, though.

### CODE REVIEW

**Comment by mleong245** [comment]
Do NOT merge this until the Cucumber feature is written properly.  See issue #18.  This PR is just set up for after it's done.

**Comment by khotchkiss13** [comment]
This branch should be good to merge now

**Comment by gabekoo** [comment]
Looks good to me

**Comment by mleong245** [comment]
Looks good to me.  Merging it in.

**Pull request merged**
