### PR TITLE
New events

### PR DESCRIPTION
**Pull request by khotchkiss13**
NOTE: DO NOT MERGE YET. STILL NEED RSPEC TESTS.
This build will fail due to someone else's feature that has yet to be implemented. 

This branch has all of the needed functionality for admin to create events, and see who has signed up to volunteer for them. 

This branch also has all of the needed functionality for confirmed volunteers to be able to sign up for events, as well as unregister for events.

### CODE REVIEW

**Comment by khotchkiss13** [comment]
Ready to be reviewed/merged

**Comment by gabekoo** [comment]
Creating events looks good to me.  After I signed up to volunteer for an event, I couldn't find a link to unvolunteer.  Might have just missed it though.  Small thing to do for later might be to add validations to the volunteer sign up form so I can't just mash my keyboard to fill it out.

**Comment by khotchkiss13** [comment]
The link to unvolunteer from an event is on the event's detail page, as it replaces the link to volunteer for it. The volunteer sign up form is Kevin's feature, so I haven't touched that, as I was just working on signing up to volunteer for specific events.

**Comment by gabekoo** [comment]
I'm only seeing the change from volunteer to unvolunteer when I'm logged in as an admin.  Can anyone else see the unvolunteer link as a volunteer?

**Comment by khotchkiss13** [comment]
In order to be an actual volunteer, you need to be approved by an admin. So, if you have not been approved, the link you should see is the form to sign up to be a "official volunteer", and if you have been approved as a volunteer, you have the ability to register to volunteer for that specific event, or unregister if you have already registered.

**Pull request merged**
